

cbuffer UnityPerMaterial 
{
    //#!INJECT_POINT MATERIAL_CBUFFER_EARLY
    float4 _BaseMap_ST;
    //#!INJECT_POINT MATERIAL_CBUFFER_FLOAT_VECTORS
    half4 _BaseColor;
    //#!INJECT_POINT MATERIAL_CBUFFER_HALF_VECTORS
    //#!INJECT_POINT MATERIAL_CBUFFER_FLOAT_SCALARS
    int _Surface;
    //#!INJECT_POINT MATERIAL_CBUFFER_HALF_SCALARS
};