//#!INJECT_BEGIN MATERIAL_CBUFFER_FLOAT_VECTORS 0
	float4 _PenMap_ST;
//#!INJECT_END

//#!INJECT_BEGIN MATERIAL_CBUFFER_HALF_VECTORS 0
	half4  _PenMonoColor;
//#!INJECT_END

//#!INJECT_BEGIN MATERIAL_CBUFFER_HALF_SCALARS 0
	half  _PenMono;
//#!INJECT_END